apiVersion: apps/v1
kind: Deployment
metadata:
  name: t3-deployment
  labels:
    app: t3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t3
  template:
    metadata:
      labels:
        app: t3
    spec:
      containers:
      - name: t3
        image: murilotico/secret:latest
        ports:
          - containerPort: 8000
        envFrom:
          - secretRef:
              name: t3-secret