apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: t41-statefulset
  namespace: task41
spec:
  serviceName: "t41-svc" # Nome do serviço associado ao StatefulSet
  replicas: 3 # Número de réplicas (pods)
  selector:
    matchLabels:
      app: t41 # Rótulo usado para selecionar os pods do StatefulSet
  template:
    metadata:
      labels:
        app: t41 # Rótulo do pod
    spec:
      containers:
        - name: t41
          image: murilotico/t41:v3 # Nome da imagem Docker
          ports:
            - containerPort: 7000 # Porta que o contêiner está ouvindo
          envFrom:
            - secretRef:
                name: t41-sct # Nome do segredo que contém as variáveis de ambiente
  volumeClaimTemplates:
    - metadata:
        name: data # Nome do volume
      spec:
        accessModes: [ "ReadWriteOnce" ] # Modo de acesso do volume
        storageClassName: standard # Classe de armazenamento
        resources:
          requests:
            storage: 1Gi # Requisição de armazenamento por réplica